#!/bin/bash

help() {
  echo "Usage:"
  echo "  zlocal-https generate [options...] [domain=localhost]"
  echo ""
  echo "Options:"
  echo "    --wildcard    Sign wildcard domain certificate"
  echo "    --self-as-ca  Self domain as ca and self signed self"
  echo ""
  echo "Example:"
  echo "    zmicro local-https generate zsxxx.com"
  echo "    zmicro local-https generate --wildcard zsxxx.com"
  echo "    zmicro local-https generate --wildcard --self-as-ca zsxxx.com"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # local domain=$1
  # if [ -z "$domain" ]; then
  #   # log::error "domain is required"
  #   # exit 1
  #   domain=localhost
  # fi

  local is_wildcard=false
  local self_as_ca=false
  local domain=""

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    --wildcard)
      os::set_var is_wildcard true
      shift
      ;;
    --self-as-ca)
      os::set_var self_as_ca true
      shift
      ;;
    *)
      if [ -n "$domain" ]; then
        log::error "ERROR: unknown parameter \"$key\""
        exit 1
      fi

      domain=$key
      shift
      ;;
    esac
  done

  if [ -z "$domain" ]; then
    log::error "[$(timestamp)] domain is required"
    exit 1
  fi

  local_https::generate $domain $is_wildcard $self_as_ca
}

run() {
  core $@
}

run $@
