#!/bin/bash

load inquirer

local_https::command_exists() {
  type "$1" &>/dev/null
}

local_https::generate() {
  set -e
  local domain=$1
  local config_dir=${PLUGIN_DIR}/config
  local ca_self_domain="local-https.root.ca.com"
  local ca_data_dir=$PLUGIN_LOCAL_HTTPS_CERTS/ca
  local ca_key=$ca_data_dir/root_ca.key
  local ca_crt=$ca_data_dir/root_ca.crt
  local ca_options=$config_dir/conf/ca/certificate-authority-options.conf

  local domain_data_dir=$PLUGIN_LOCAL_HTTPS_CERTS/domain/$domain
  local domain_server_ca_options=$domain_data_dir/certificate-authority-options.conf
  local domain_server_options=$domain_data_dir/options.conf
  local domain_server_key=$domain_data_dir/server.key
  local domain_server_csr=$domain_data_dir/server.csr
  local domain_server_crt=$domain_data_dir/server.crt
  # local data_tmp=$domain_data_dir/tmp

  log::info "generate https(ssl) for domain (${domain}) ..."

  if [ ! -d "$ca_data_dir" ]; then
    mkdir -p $ca_data_dir
  fi

  if [ ! -d "$domain_data_dir" ]; then
    mkdir -p $domain_data_dir
  fi

  # if [ ! -d $data_tmp ]; then
  #   mkdir -p $data_tmp
  # else
  #   rm -rf $data_tmp
  #   mkdir -p $data_tmp
  # fi

  local cao=certificate-authority-options.conf
  local options_conf=options.conf

  cd $domain_data_dir

  log::info "tips: use the same pass phrase for the following steps ..."

  if [ ! -f "$ca_key" ]; then
    log::info "generate ca private key ..."
    # need password
    # openssl genrsa -des3 -out "$ca_key" 2048 >> /dev/null 2>&1
    # no password
    openssl genrsa -out "$ca_key" 2048 >>/dev/null 2>&1
  fi

  if [ ! -f "$ca_crt" ]; then
    # 注意：证书颁发机构 CA 有效时间不受苹果系统域名 825 天限制，也就是可以是 3650 天（10年），与下文签发具体域名证书对比
    log::info "generate ca certtificate ..."
    openssl req -x509 \
      -config $ca_options \
      -new -nodes \
      -key "$ca_key" \
      -sha256 \
      -days 3650 \
      -out "$ca_crt" >>/dev/null 2>&1
    # -days 825 \
  fi

  # MacOS
  if local_https::command_exists security; then
    log::info "write self signed ca to system ..."

    if [ "$(sudo security find-certificate -c "${ca_self_domain}" -a -Z)" = "" ]; then
      # Delete trusted certs by their common name via https://unix.stackexchange.com/a/227014
      sudo security find-certificate -c "${ca_self_domain}" -a -Z | sudo awk '/SHA-1/{system("security delete-certificate -Z "$NF)}'

      # Trust the Root Certificate cert
      sudo security add-trusted-cert \
        -d \
        -r trustRoot \
        -k /Library/Keychains/System.keychain \
        "$ca_crt"
    fi
  elif local_https::command_exists dpkg-reconfigure; then
    local YesNo=(Yes No)
    inquirer::select "Please check $($ca_crt) in next step, are you ready ?" YesNo ok
    if [ "$ok" != "Yes" ]; then
      log::error "You have cancel it"
      exit 1
    fi

    sudo copy $ca_crt /usr/share/ca-certificates/$ca_crt
    sudo dpkg-reconfigure ca-certificates
  fi

  if [ ! -f "$domain_server_key" ]; then
    log::info "generate private key for ${domain} ..."
    # Generate Server Privatekey (服务器私钥)
    openssl genrsa -out "$domain_server_key" 2048 >>/dev/null 2>&1
  fi

  log::info "preparing config ..."
  # Remove any lines that start with CN
  sed '/^CN/ d' $config_dir/conf/domain/$cao >$domain_server_ca_options
  # Modify the conf file to set CN = ${name}
  echo "CN = ${domain}" >>$domain_server_ca_options
  #
  sed "s/local.dev/"$domain"/" $config_dir/conf/domain/$options_conf >$domain_server_options

  # Generate CA-signed Request (服务器证书签名请求)
  openssl req \
    -new \
    -config $domain_server_ca_options \
    -key "$domain_server_key" \
    -out "$domain_server_csr" >>/dev/null 2>&1

  log::info "generate self signed certificate for ${domain} ..."
  # Generate CA-signed SSL Certificate (通过 CSR 向 CA 签发服务端证书)
  #
  # 注意：苹果系统限制，必须使用 SHA256 且域名证书必须小于 825 天，也就是说不能签发 10 年的域名证书，但不影响上面的 CA
  # Certificates last for 2 years and 3 months, which is always less than
	# 825 days, the limit that macOS/iOS apply to all certificates,
	# including custom roots. See https://support.apple.com/en-us/HT210176.
  openssl x509 \
    -req \
    -CA "$ca_crt" \
    -CAkey "$ca_key" \
    -CAcreateserial \
    -days 825 \
    -sha256 \
    -extfile $domain_server_options \
    -in "$domain_server_csr" \
    -out "$domain_server_crt" >>/dev/null 2>&1

  log::info "clean ..."
  # Cleanup a stray file
  rm -rf $domain_data_dir/*.srl
  rm -rf $domain_server_csr

  # The username behind sudo, to give ownership back
  # local user=$(os::username)
  # chown -R "$user" .*

  log::success "register local https for $domain done"
  echo ""
  log::success "#####################################"
  log::success "# ssl key: $domain_server_key"
  log::success "# ssl key: $domain_server_crt"
  log::success "#####################################"
  echo ""

  set +e
}

export -f local_https::command_exists
export -f local_https::generate
